- nx.json
> fix(qwik-nx): fix build on new version

- .vscode/settings.json
- packages/qwik-nx/package.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
generated apps need @nrwl/vite as a dependency, so I moved it from
> fix: moved vite to dependencies

- packages/qwik-nx/src/generators/setup-tailwind/files/postcss.config.js__tmpl__
- packages/qwik-nx/src/generators/setup-tailwind/files/tailwind.config.js__tmpl__
Currently tailwind configuration does not use proper paths, fixing this
> fix: update tailwind config

- CONTRIBUTING.md
- [√] Docs / tests
Add clarity to Publishing to a local registry docs.
Was not clear
- [√] I have performed a self-review of my own code
- [√] I have made corresponding changes to the documentation
> docs: clarify "Publishing to a local registry"

- packages/qwik-nx/src/generators/application/utils/get-qwik-application-project-params.ts
in continuation of this discussion https://github.com/qwikifiers/qwik-nx/issues/39
> feat: add debug target

- e2e/qwik-nx-e2e/tests/application-basic-behavior.suite.ts
- e2e/qwik-nx-e2e/tests/preset.spec.ts
- e2e/qwik-nx-e2e/tsconfig.spec.json
app and preset generators generally follow the same purpose with minor differences. Applying existing app generator tests to the preset generator as well.
> test(qwik-nx): run the same basic tests for both "app" and "preset" generators

- packages/qwik-nx/src/generators/application/generator.ts
- packages/qwik-nx/src/generators/library/generator.ts
- packages/qwik-nx/src/utils/ensure-tsconfig-base-exists.ts
tsconfig.base.json is not present in package-based nx repo by default, so make sure it's avaialble when qwik-nx generators are run
closes https://github.com/qwikifiers/qwik-nx/issues/90
> feat(qwik-nx): ensure tsconfig.base.json exists in a package-based repo

- packages/qwik-nx/src/generators/application/__snapshots__/generator.spec.ts.snap
- packages/qwik-nx/src/generators/application/files/vite.config.ts__template__
- packages/qwik-nx/src/generators/component/files/common/__fileName__.tsx.template
- packages/qwik-nx/src/generators/component/files/tests/__fileName__.spec.tsx.template
- packages/qwik-nx/src/generators/host/__snapshots__/generator.spec.ts.snap
- packages/qwik-nx/src/generators/library/__snapshots__/generator.spec.ts.snap
- packages/qwik-nx/src/generators/library/files/vite.config.ts.template
- packages/qwik-nx/src/generators/library/generator.spec.ts
- packages/qwik-nx/src/generators/library/generator.ts
- packages/qwik-nx/src/generators/library/schema.d.ts
- packages/qwik-nx/src/generators/library/schema.json
- packages/qwik-nx/src/generators/library/utils/get-qwik-lib-project-params.ts
- packages/qwik-nx/src/generators/library/utils/normalize-options.ts
- packages/qwik-nx/src/generators/remote/__snapshots__/generator.spec.ts.snap
Adding support for non-buildable qwik libraries
> feat(qwik-nx): non buildable libs

- packages/qwik-nx/migrations.json
- packages/qwik-nx/src/utils/versions.ts
added auto migration to latest qwik
> feat: add migration to qwik 0.23.0

- packages/qwik-nx/src/plugins/qwik-nx-vite.plugin.spec.ts
- packages/qwik-nx/src/plugins/qwik-nx-vite.plugin.ts
QwikNxVite plugin should not include its project as a vendor root for itself
> fix(qwik-nx): vite plugin exclude its project as a vendor root

- packages/qwik-nx/src/generators/storybook-configuration/__snapshots__/generator.spec.ts.snap
- packages/qwik-nx/src/generators/storybook-configuration/files/.storybook/main.__configExtension__.template
- packages/qwik-nx/src/generators/storybook-configuration/files/.storybook/preview-head.html.template
- packages/qwik-nx/src/generators/storybook-configuration/files/.storybook/preview.__configExtension__.template
- packages/qwik-nx/src/generators/storybook-configuration/generator.spec.ts
- packages/qwik-nx/src/generators/storybook-configuration/generator.ts
- packages/qwik-nx/src/generators/storybook-configuration/schema.d.ts
- packages/qwik-nx/src/generators/storybook-configuration/schema.json
- packages/qwik-nx/src/utils/storybook.ts
- packages/qwik-nx/storybook.ts
- adding qwikCity storybook decorator as an option
- qwikCity transform should not be executed in storybook
closes #118
> fix(qwik-nx): storybook updates for qwikCity

- packages/qwik-nx/src/utils/storybook.ts
Storybook build artifacts are being put in different folders right now, because `qwikVite` plugin from the main config is being pulled from the main vite.config.ts with `client.outDir = "../../dist/apps/.../client"`.
Instead, `qwikVite` should be overridden  in .storybook/main.ts under the hood by withNx function with a new instance of a plugin.
> fix(qwik-nx): override qwikVite plugin for storybook

- e2e/qwik-nx-e2e/tests/__snapshots__/application.spec.ts.snap
- e2e/qwik-nx-e2e/tests/__snapshots__/preset.spec.ts.snap
- e2e/qwik-nx-e2e/tests/application-basic-behavior.suite.ts
- e2e/qwik-nx-e2e/tsconfig.spec.json
- packages/qwik-nx/src/executors/build/executor.spec.ts
- packages/qwik-nx/src/executors/build/executor.ts
- packages/qwik-nx/src/executors/build/schema.d.ts
- packages/qwik-nx/src/executors/build/schema.json
closes https://github.com/qwikifiers/qwik-nx/issues/142
> feat(qwik-nx): build executor should run type checking

- packages/qwik-nx/src/generators/route/files/layout/__routeName__/layout.tsx__template__
> fix: add missing import

- packages/qwik-nx/src/utils/add-common-qwik-dependencies.ts
Fix issue with failing build as outlined in #167.
> fix(deps): add @types/node

- e2e/qwik-nx-e2e/tests/qwik-nx-netlify.spec.ts
- packages/qwik-nx/executors.json
- packages/qwik-nx/generators.json
- packages/qwik-nx/src/executors/exec/executor.ts
- packages/qwik-nx/src/executors/exec/schema.d.ts
- packages/qwik-nx/src/executors/exec/schema.json
- packages/qwik-nx/src/generators/integrations/cloudflare-pages-integration/generator.ts
- packages/qwik-nx/src/generators/integrations/netlify/__snapshots__/generator.spec.ts.snap
- packages/qwik-nx/src/generators/integrations/netlify/files/adapters/netlify/vite.config.ts.template
- packages/qwik-nx/src/generators/integrations/netlify/files/public/_headers.template
- packages/qwik-nx/src/generators/integrations/netlify/files/src/entry.netlify-edge.tsx.template
- packages/qwik-nx/src/generators/integrations/netlify/generator.spec.ts
- packages/qwik-nx/src/generators/integrations/netlify/generator.ts
- packages/qwik-nx/src/generators/integrations/netlify/schema.d.ts
- packages/qwik-nx/src/generators/integrations/netlify/schema.json
- packages/qwik-nx/src/utils/integration-configuration-name.ts
- packages/qwik-nx/src/utils/migrations.ts
- packages/qwik-nx/src/utils/versions.ts
- pnpm-lock.yaml
> feat(qwik-nx): netlify integration

- packages/qwik-nx/src/generators/application/files/src/routes/flower/flower.__styleExtension____template__
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
- 1. One use case
> fix(qwik-nx): remove duplicate css variable

- packages/qwik-nx/CHANGELOG.md
- packages/qwik-nx/package.json
This reverts commit 924ecfe7a23468b4bf5fde3aa026ca91bee70c8d.
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
- 1. One use case
> Revert "chore(qwik-nx): release version 1.0.9"

- packages/qwik-nx/src/generators/application/files/src/entry.preview.tsx__template__
RouterLoaders in layout files were broken for the preview mode, see: https://github.com/BuilderIO/qwik/issues/3634
closes https://github.com/qwikifiers/qwik-nx/issues/203
> Fix preview issues with routerLoaders

- README.md
This repository has a generator for storybook but it doesn't really mention it. You have to search the repository to even find anything about it
> Add storybook documentation

- .github/actions/setup/action.yml
- package.json
- pnpm-lock.yaml
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
- 1. One use case
> chore(repo): bump pnpm to 9.7.0

- .github/workflows/test.yml
I still don't know how to use verdaccio 🙈 I believe pkg.pr.new is more user friendly than verdaccio or pnpm link.
Looks like this will require merging #233 first.
- 1. One use case
> chore(repo): add pkg.pr.new
