qwikifiers/qwik-nx

- .github/workflows/test.yml
When pushing a commit to the existing PR, CI is being triggered twice, because it's both "push" and "pull_request" events. Instead, "push" event should only be triggered for the "main" branch
> chore(ci): do not trigger CI twice in pull requests

- packages/qwik-nx/src/generators/component/generator.ts
https://github.com/qwikifiers/qwik-nx/issues/23
Generating new components goes to the app folder instead of components.
- Actual
- Expected
> fix(component): fix folder location for generated qwik cmp

- packages/qwik-nx/src/generators/application/schema.json
Tailwind option is included in both `preset` and `application` generators, but is actually exposed only in `preset` one
> fix: expose "tailwind" option in application generator

- packages/qwik-nx/src/generators/application/generator.spec.ts
- packages/qwik-nx/src/generators/application/generator.ts
- packages/qwik-nx/src/generators/init/init.spec.ts
- packages/qwik-nx/src/generators/init/init.ts
All install tasks should be executed sequentially in the end. Running them in other places resulted in installation commands running multiple times and also failed unit tests
> fix: run all installation commands in serial

- packages/qwik-nx/src/generators/application/utils/get-qwik-application-project-params.ts
`preview-server` executor merges configuration options from itself and corresponding build target. Because of this we end up having `ssr` option in the preview configuration, which ends up having wrong dist path to serve the build assets. There's no quick fix that can be applied, so in order to not create confusion it's better to revert the change entirely
> Revert "feat: use @nrwl/vite:preview-server executor (#47)"

- .github/workflows/test.yml
Should cancel previous checks for PR when branch is pushed/force-pushed
> chore: cancel previous CI runs in PRs

- e2e/qwik-nx-e2e/tests/chore.spec.ts
- packages/qwik-nx/package.json
- packages/qwik-nx/src/generators/preset/schema.json
1. when running `npx create-nx-workspace somename --preset-qwik-nx`, qwik-nx:preset generator uses default argument `somename` for the application name, while it is supposed to only be used for the workspace name
2. @nrwl/js:tsc executor builds qwik-nx package and includes dependencies of dependencies in its package.json. SInce this is happening, we should at least specify wider range of dependencies in order to not limit users to a single strict version
> fix(qwik-nx): preset and peer dependencies fixes

- packages/qwik-nx/src/generators/setup-tailwind/files/tailwind.config.js__tmpl__
Added a missing import statement `const { join } = require('path');` in the `tailwind.config.js__tmpl__` which is causing this error - https://github.com/qwikifiers/qwik-nx/issues/70
When tailwind is added via generator there should not be any errors.
closes https://github.com/qwikifiers/qwik-nx/issues/70
> fix(qwik-nx): added missing path import statement for tailwind template

- package.json
- packages/qwik-nx/src/utils/versions.ts
- pnpm-lock.yaml
- tsconfig.base.json
Updates NxKit to v2.1.1 to include fix in nxkit/nxkit#59 allowing to install the packages dynamically.
- 1. Context in #44
Fixes #44
> fix(qwik-nx): update nxkit to v2.1.1

- e2e/qwik-nx-e2e/tests/chore.spec.ts
- e2e/utils/index.ts
- packages/qwik-nx/package.json
- packages/qwik-nx/src/utils/add-common-qwik-dependencies.ts
- packages/qwik-nx/src/utils/versions.ts
- updated qwik and its related dependencies to latest versions
- moved @nrwl/vite to the peer dependencies, we don't want to depend on a strict version of this package
> feat(qwik-nx): bump up versions of the dependencies

- packages/qwik-nx/src/generators/preset/schema.json
required property name is invalid
> fix(qwik-nx): fix the name of the required name prop of preset generator

- packages/qwik-nx/src/plugins/qwik-nx-vite.plugin.spec.ts
- packages/qwik-nx/src/plugins/qwik-nx-vite.plugin.ts
By default `qwikNxVite` plugin will provide Qwik with paths of all Nx projects, that are specified in the tsconfig.base.json.
However, this behavior might not be always suitable, especially in cases when there's code that you don't want the optimizer to go through (for example, Angular components). Adding filter options in order to be able to exclude such libs from the list that is provided to the Qwik
```typescript
plugins: [
...
qwikNxVite({
includeProjects: { name: /^shared/, tags: ['scope:shared'] },
excludeProjects: { name: ['tmp-test-lib-b'] },
})
]
```
> feat(qwik-nx): add projects filter for qwikNxVite plugin

- e2e/qwik-nx-e2e/tests/chore.spec.ts
- packages/qwik-nx/package.json
@nrwl/vite package may not be fully compatible between versions, so it is much safer to use approximate version instead of compatible
> fix(qwik-nx): use approximate version for @nrwl/vite package

- packages/qwik-nx/src/utils/configure-eslint.ts
If eslint files don't exist in the repository, `configureEslint` may fail. To prevent this, it's required to firstly check for file existance
> fix(qwik-nx): check for eslint file existance before reading it

- e2e/qwik-nx-e2e/tests/application-basic-behavior.suite.ts
- e2e/qwik-nx-e2e/tests/qwik-nx-vite.spec.ts
- e2e/utils/index.ts
- packages/qwik-nx/.eslintrc.json
- packages/qwik-nx/executors.json
- packages/qwik-nx/migrations.json
- packages/qwik-nx/package.json
- packages/qwik-nx/project.json
- packages/qwik-nx/src/executors/build/executor.spec.ts
- packages/qwik-nx/src/executors/build/executor.ts
- packages/qwik-nx/src/executors/build/schema.d.ts
- packages/qwik-nx/src/executors/build/schema.json
- packages/qwik-nx/src/generators/application/utils/get-qwik-application-project-params.ts
- packages/qwik-nx/src/generators/integrations/cloudflare-pages-integration/generator.spec.ts
- packages/qwik-nx/src/generators/integrations/cloudflare-pages-integration/generator.ts
- packages/qwik-nx/src/migrations/switch-to-qwik-nx:build-executor/switch-to-qwik-nx:build-executor.spec.ts
- packages/qwik-nx/src/migrations/switch-to-qwik-nx:build-executor/switch-to-qwik-nx:build-executor.ts
- packages/qwik-nx/src/utils/integration-configuration-name.ts
Adding a new build executor, that will unify the flow to build the Qwik project in a similar way how it's done with original qwik apps with Qwik CLI. 
The new executor wraps `build.client` and `build.ssr` targets into `build` executor, where they can both be executed sequentially. It also allows to project `build`'s target configuration to the ones it invokes.
With this change the commands will be as follows:
- nx preview my-app - builds the app in the preview mode and runs the preview server
- nx run my-app:build or nx run my-app:build:preview - builds the app in the preview mode
- nx build my-app --prod or nx run my-app:build:production - builds the app in a cloudflare mode. This is the main change: if there're no integrations, the one that is being added will get a "production" mode as …
> feat(qwik-nx): build executor

- .verdaccio/config.yml
- .verdaccio/htpasswd
- CONTRIBUTING.md
- package.json
- packages/qwik-nx/project.json
- pnpm-lock.yaml
- scripts/local-registry.sh
Right now the description of local publishing is completely irrelevant, it's not possible to run it in the way it is described in our docs. 
Additionally to this working with verdaccio might not be that straightforward, because it is needed to explicitly specify what registry to pull from, how to clean it and so on.
Instead of this it might be better to use the same approach Nx team has in their repository: the bash script that will allow to run few plain commands to start/stop/clean the local registry. 
Publishing process itself is also improved: prior to this PR I have created a pull to ngx-deploy-npm adding the `registry` option. With this in place, starting from `ngx-deploy-npm@5.2.0` it is now possible to publish to another registry using nx target configuration (`nx run …
> chore: fix local package publishing

- packages/qwik-nx/src/generators/preset/generator.spec.ts
- packages/qwik-nx/src/generators/preset/generator.ts
- packages/qwik-nx/src/utils/get-installed-nx-version.ts
When repository is created, peer dependencies are not installed by default. Because of this `@nrwl/vite` is not available and an error is thrown. 
Along with this checking for the installed nx version should be improved: it's not enough to check for the presence of `@nrwl/workspace` in devDependencies
closes https://github.com/qwikifiers/qwik-nx/issues/89
> fix(qwik-nx): preset generator should check for the presense of peerDeps

- .gitignore
`migrations.json` file was added into `.gitignore`, because of this it wasn't included in the built package
> fix(qwik-nx): migrations.json should not be ignored

- .gitignore
- package.json
- packages/qwik-nx/migrations.json
- packages/qwik-nx/src/migrations/update-use-client-effect$-to-use-visisble-task$/update-use-client-effect$-to-use-visisble-task$.spec.ts
- packages/qwik-nx/src/migrations/update-use-client-effect$-to-use-visisble-task$/update-use-client-effect$-to-use-visisble-task$.ts
- pnpm-lock.yaml
Add the ability to auto-update the qwik version and its dependencies
> feat: added deps migration

- CONTRIBUTING.md
- README.md
- e2e/qwik-nx-e2e/tests/chore.spec.ts
- packages/qwik-nx/migrations.json
- packages/qwik-nx/package.json
- packages/qwik-nx/src/plugins/qwik-nx-vite.plugin.ts
- packages/qwik-nx/src/utils/versions.ts
- bumping qwik dependencies to version 0.21, which addresses critical vulnerability
- removed unnecessary peer dependencies
> feat(qwik-nx): bump qwik deps and exclude qwik package from peer dependencies

- e2e/qwik-nx-e2e/tests/storybook.spec.ts
- packages/qwik-nx/src/generators/application/generator.spec.ts
- packages/qwik-nx/src/generators/component/__snapshots__/generator.spec.ts.snap
- packages/qwik-nx/src/generators/component/files/common/__fileName__.tsx.template
- packages/qwik-nx/src/generators/component/files/storybook/__fileName__.doc.mdx.template
- packages/qwik-nx/src/generators/component/files/storybook/__fileName__.stories.tsx.template
- packages/qwik-nx/src/generators/component/files/tests/__fileName__.spec.tsx.template
- packages/qwik-nx/src/generators/component/generator.spec.ts
- packages/qwik-nx/src/generators/component/generator.ts
- packages/qwik-nx/src/generators/component/schema.d.ts
- packages/qwik-nx/src/generators/component/schema.json
- packages/qwik-nx/src/generators/host/generator.spec.ts
- packages/qwik-nx/src/generators/library/generator.spec.ts
- packages/qwik-nx/src/generators/remote/generator.spec.ts
- packages/qwik-nx/src/generators/storybook-configuration/generator.spec.ts
- packages/qwik-nx/src/utils/testing-generators.ts
Adding an ability to generate components with default export instead of a named one
closes #116
> feat(qwik-nx): default export option for component generator

- e2e/qwik-nx-e2e/tests/chore.spec.ts
- package.json
- packages/qwik-nx/package.json
- packages/qwik-nx/project.json
- packages/qwik-nx/src/generators/preset/generator.spec.ts
- packages/qwik-nx/src/generators/preset/generator.ts
- packages/qwik-nx/src/utils/get-installed-nx-version.ts
`@nrwl/*` packages that are specified as peer dependencies of `qwik-nx` package are crucial to execute any of the package's generators, thus it makes much more sense to keep them as `dependencies` instead. By adding `updateBuildableProjectDepsInPackageJson` property to project's build target it is possible to make nx executor to not override versions (as it was before).
> feat(qwik-nx): move peer dependencies to dependencies

- packages/qwik-nx/src/plugins/index.ts
- packages/qwik-nx/src/plugins/models/qwik-nx-vite.ts
- packages/qwik-nx/src/plugins/qwik-nx-vite.plugin.spec.ts
- packages/qwik-nx/src/plugins/qwik-nx-vite.plugin.ts
- packages/qwik-nx/src/plugins/utils/current-project-name.ts
- packages/qwik-nx/src/plugins/utils/filter-projects.ts
- packages/qwik-nx/src/plugins/utils/get-project-dependencies.ts
- packages/qwik-nx/src/plugins/utils/get-vendor-roots.ts
Right now by default qwikNxVite plugin will include all projects from the workspace as vendorRoots. 
This PR changes the default behavior to only include those projects that are recognized by Nx as dependencies of the particular app. In other words, it works like a reversed nx `affected`
> feat(qwik-nx): qwikNxVite plugin to include only project's dependencies  by default

- packages/qwik-nx/generators.json
- packages/qwik-nx/src/generators/integrations/react-in-app/__snapshots__/generator.spec.ts.snap
- packages/qwik-nx/src/generators/integrations/react-in-app/files/demo/index.tsx.template
- packages/qwik-nx/src/generators/integrations/react-in-app/files/mui/index.tsx.template
- packages/qwik-nx/src/generators/integrations/react-in-app/generator.spec.ts
- packages/qwik-nx/src/generators/integrations/react-in-app/generator.ts
- packages/qwik-nx/src/generators/integrations/react-in-app/schema.d.ts
- packages/qwik-nx/src/generators/integrations/react-in-app/schema.json
- packages/qwik-nx/src/generators/integrations/react-library/__snapshots__/generator.spec.ts.snap
- packages/qwik-nx/src/generators/integrations/react-library/files/src/index.ts.template
- packages/qwik-nx/src/generators/integrations/react-library/generator.spec.ts
- packages/qwik-nx/src/generators/integrations/react-library/generator.ts
- packages/qwik-nx/src/generators/integrations/react-library/schema.d.ts
- packages/qwik-nx/src/generators/integrations/react-library/schema.json
- packages/qwik-nx/src/generators/library/generator.ts
- packages/qwik-nx/src/generators/library/schema.d.ts
- packages/qwik-nx/src/generators/library/utils/normalize-options.ts
- packages/qwik-nx/src/generators/storybook-configuration/generator.ts
- packages/qwik-nx/src/utils/react/files/demo/demo.tsx.template
- packages/qwik-nx/src/utils/react/files/mui/mui.tsx.template
- packages/qwik-nx/src/utils/react/init.ts
- packages/qwik-nx/src/utils/update-vite-config.spec.ts
- packages/qwik-nx/src/utils/update-vite-config.ts
- packages/qwik-nx/src/utils/versions.ts
Adding an ability to use qwikify react functionality in qwik nx apps.
This includes 2 generators: 
- `react-in-app` generator behaves in the same manner as native qwik integration, it will add `integrations/react` folder in the existing qwik app
- `react-library` generator will create a separate library to keep qwikified components in it
closes https://github.com/qwikifiers/qwik-nx/issues/36
> feat(qwik-nx): react integration

- packages/qwik-nx/src/generators/application/files/src/components/router-head/router-head.tsx__template__
`useLocation()` returns us a `RouteLocation` instance. So we should get the href from `loc.url.href`.
```ts
export declare interface RouteLocation {
readonly params: Readonly<Record<string, string>>;
readonly url: URL;
readonly isNavigating: boolean;
}
```
- 1. Generate qwik application by running `nx generate qwik-nx:application`
> fix(qwik-nx): get canonical url from the right path

- e2e/qwik-nx-e2e/tests/qwik-nx-cloudflare.spec.ts
- packages/qwik-nx/src/generators/integrations/cloudflare-pages-integration/files/adapters/cloudflare-pages/vite.config.ts.template
The generator for Cloudflare had a couple of problems with the adapter `vite.config.ts` file. These are the changes made.
- The adapter name was renamed from `cloudflarePagesAdaptor` to `cloudflarePagesAdapter`
- The SSG configuration was removed since that's not longer a valid property, and SSG is on by default.
Fixes: #174 
The generated content has issues. and not allowed to build the apps.
The generated content is correct and allows to build and deploy to Cloudflare.
> fix: vite.config for cloudflare adapter miss-configurations

- .gitignore
- e2e/qwik-nx-e2e/tests/chore.spec.ts
- e2e/utils/index.ts
- package.json
- packages/qwik-nx/migrations.json
- packages/qwik-nx/src/generators/application/__snapshots__/generator.spec.ts.snap
- packages/qwik-nx/src/generators/application/files/src/components/router-head/router-head.tsx__template__
- packages/qwik-nx/src/generators/application/files/vite.config.ts__template__
- packages/qwik-nx/src/generators/host/__snapshots__/generator.spec.ts.snap
- packages/qwik-nx/src/generators/integrations/react-in-app/__snapshots__/generator.spec.ts.snap
- packages/qwik-nx/src/generators/integrations/react-library/__snapshots__/generator.spec.ts.snap
- packages/qwik-nx/src/generators/remote/__snapshots__/generator.spec.ts.snap
- packages/qwik-nx/src/migrations/set-proper-tsconfig-path-for-qwik-vite-plugin/__snapshots__/set-proper-tsconfig-path-for-qwik-vite-plugin.spec.ts.snap
- packages/qwik-nx/src/migrations/set-proper-tsconfig-path-for-qwik-vite-plugin/set-proper-tsconfig-path-for-qwik-vite-plugin.spec.ts
- packages/qwik-nx/src/migrations/set-proper-tsconfig-path-for-qwik-vite-plugin/set-proper-tsconfig-path-for-qwik-vite-plugin.ts
- packages/qwik-nx/src/plugins/qwik-nx-vite.plugin.spec.ts
- packages/qwik-nx/src/utils/versions.ts
- pnpm-lock.yaml
closes https://github.com/qwikifiers/qwik-nx/issues/201
> fix(qwik-nx): handle eslint checks in dev mode

- packages/qwik-nx/src/plugins/qwik-nx-vite.plugin.ts
closes https://github.com/qwikifiers/qwik-nx/issues/236
> fix(qwik-nx): handle absence of vendor roots

- packages/qwik-nx/src/plugins/qwik-nx-vite.plugin.spec.ts
- packages/qwik-nx/src/plugins/utils/current-project-name.ts
- packages/qwik-nx/src/plugins/utils/get-vendor-roots.ts
In our CI, we face a sporadic timeout issue when running a test target that involves `qwikNxVite`. This change fixes the problem by using the right way to get the project graph and project configs, dropping the deprecated `readWorkspaceConfig` API in favor of the devkit.
Note that [Nx 21 removed the function](https://github.com/nrwl/nx/commit/840aef802f9bfd73828434d69d786ceae812b50e#diff-e3dbf0bc765b8ab61c9b38cca6f1f106839b76adba63590f2dc00ac339fdd5e5L192), so it's a needed refactoring anyway.
No sporadic timeout issue when running a test target including  `qwikNxVite`.
> fix(qwik-nx): drop deprecated `readWorkspaceConfig` in favor of `readCachedProjectGraph`

- packages/qwik-nx/src/generators/application/files/vite.config.ts__template__
- packages/qwik-nx/src/generators/host/__snapshots__/generator.spec.ts.snap
- packages/qwik-nx/src/generators/integrations/react-in-app/__snapshots__/generator.spec.ts.snap
- packages/qwik-nx/src/generators/integrations/react-library/__snapshots__/generator.spec.ts.snap
- packages/qwik-nx/src/generators/library/__snapshots__/generator.spec.ts.snap
- packages/qwik-nx/src/generators/library/files/vite.config.ts.template
- packages/qwik-nx/src/generators/remote/__snapshots__/generator.spec.ts.snap
When generating anything, the vitest config doesn't come with the default reporter, so you don't get any output for successful/failed tests at all. 
Closes: https://github.com/qwikifiers/qwik-nx/issues/253
- 1. Running tests should provide an output for what succeeded/failed
> fix(qwik-nx): add default reporter for vitest config
